require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AmpluasController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Amplua. As you add validations to Amplua, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AmpluasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ampluas as @ampluas" do
      amplua = Amplua.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:ampluas)).to eq([amplua])
    end
  end

  describe "GET show" do
    it "assigns the requested amplua as @amplua" do
      amplua = Amplua.create! valid_attributes
      get :show, {:id => amplua.to_param}, valid_session
      expect(assigns(:amplua)).to eq(amplua)
    end
  end

  describe "GET new" do
    it "assigns a new amplua as @amplua" do
      get :new, {}, valid_session
      expect(assigns(:amplua)).to be_a_new(Amplua)
    end
  end

  describe "GET edit" do
    it "assigns the requested amplua as @amplua" do
      amplua = Amplua.create! valid_attributes
      get :edit, {:id => amplua.to_param}, valid_session
      expect(assigns(:amplua)).to eq(amplua)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Amplua" do
        expect {
          post :create, {:amplua => valid_attributes}, valid_session
        }.to change(Amplua, :count).by(1)
      end

      it "assigns a newly created amplua as @amplua" do
        post :create, {:amplua => valid_attributes}, valid_session
        expect(assigns(:amplua)).to be_a(Amplua)
        expect(assigns(:amplua)).to be_persisted
      end

      it "redirects to the created amplua" do
        post :create, {:amplua => valid_attributes}, valid_session
        expect(response).to redirect_to(Amplua.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved amplua as @amplua" do
        post :create, {:amplua => invalid_attributes}, valid_session
        expect(assigns(:amplua)).to be_a_new(Amplua)
      end

      it "re-renders the 'new' template" do
        post :create, {:amplua => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested amplua" do
        amplua = Amplua.create! valid_attributes
        put :update, {:id => amplua.to_param, :amplua => new_attributes}, valid_session
        amplua.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested amplua as @amplua" do
        amplua = Amplua.create! valid_attributes
        put :update, {:id => amplua.to_param, :amplua => valid_attributes}, valid_session
        expect(assigns(:amplua)).to eq(amplua)
      end

      it "redirects to the amplua" do
        amplua = Amplua.create! valid_attributes
        put :update, {:id => amplua.to_param, :amplua => valid_attributes}, valid_session
        expect(response).to redirect_to(amplua)
      end
    end

    describe "with invalid params" do
      it "assigns the amplua as @amplua" do
        amplua = Amplua.create! valid_attributes
        put :update, {:id => amplua.to_param, :amplua => invalid_attributes}, valid_session
        expect(assigns(:amplua)).to eq(amplua)
      end

      it "re-renders the 'edit' template" do
        amplua = Amplua.create! valid_attributes
        put :update, {:id => amplua.to_param, :amplua => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested amplua" do
      amplua = Amplua.create! valid_attributes
      expect {
        delete :destroy, {:id => amplua.to_param}, valid_session
      }.to change(Amplua, :count).by(-1)
    end

    it "redirects to the ampluas list" do
      amplua = Amplua.create! valid_attributes
      delete :destroy, {:id => amplua.to_param}, valid_session
      expect(response).to redirect_to(ampluas_url)
    end
  end

end
